services:
  - type: web
    name: atelier-app
    env: node
    rootDir: .
    buildCommand: npm ci && npm run build:prod
    startCommand: npm start
    envVars:
      - key: TOKEN
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
